### ISSUE TITLE
Split-view preview ignoring some styles 

### ISSUE THREAD

**Issue by kdholland** [superhi/editor-issues#11]
**Describe the bug**
Split-view preview ignoring some styles 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a project (mine = https://subeditor.superhi.com/projects/38766 / https://k-found-4.superhi.com/ )
2. Compare split view to full preview

**Screenshots**
Split view preview is missing font styles, space around the logo, `selected` class styling (and possibly more.)

**Device:**
 - OS: macOS 10.14.5
 - Browser: Chrome 75.0.3770.100

**Comment by artcommacode** [comment]
Hi @kdholland, I'm afraid I'm unable to reproduce this myself so I'm wondering if your stylesheets might've gotten out-of-order? We no longer order them for users and instead let them drag and drop them within the folder. 

<img width="1552" alt="Screenshot 2019-07-11 at 09 20 35" src="https://user-images.githubusercontent.com/1155516/61034572-6f1f9d00-a3bd-11e9-97e9-4e0c25a69795.png">

**Comment by kdholland** [comment]
right! reordering these fixed my issue. closing this one out. as discussed on slack we may want to think about locking `base.css` file to the top if possible - i think this one will come up again with students.

(also sorry, i had included screenshots but most have posted before they uploaded!)
