### ISSUE TITLE
Resize button still shows when preview is hidden

### ISSUE THREAD

**Issue by kdholland** [superhi/editor-issues#12]
**Describe the bug**
Resize button still shows when preview is hidden.

**To Reproduce**
Steps to reproduce the behaviour:
1. Click the eye icon to hide the preview.
2. Resize button is still there.

**Expected behaviour**
Resize button should disappear when the preview is hidden as there's nothing to resize.

**Screenshots**
![resize_button](https://user-images.githubusercontent.com/31701255/61827297-2f7f9900-ae32-11e9-8c54-29b657134c1e.gif)

**Device (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser: Google Chrome 75.0.3770.142

**Comment by artcommacode** [comment]
@kdholland this has now been fixed. The resize handle will hide itself when the preview is hidden.
