### ISSUE TITLE
Image assets not loading in Settings dropdowns

### ISSUE THREAD

**Issue by kdholland** [superhi/editor-issues#13]
**Describe the bug**
When you go to your project settings, you can't set the default sharing image, favicon, or home screen icon because the project's images do not appear in the dropdown.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a project with images.
2. Go to project settings.
3. Click on any of the dropdowns that should have images. 

**Expected behaviour**
Project images appear in dropdown:
![image](https://user-images.githubusercontent.com/31701255/61877258-a497b080-aebc-11e9-8444-02858123cb94.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/31701255/61877165-70bc8b00-aebc-11e9-8a7f-ea9cff49273e.png)
![image](https://user-images.githubusercontent.com/31701255/61877281-b37e6300-aebc-11e9-8801-8b6b244c5015.png)
![image](https://user-images.githubusercontent.com/31701255/61877318-c4c76f80-aebc-11e9-82f2-8f6ddf26d2de.png)

**Device (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser: Google Chrome  75.0.3770.142

**Comment by artcommacode** [comment]
@kdholland the image selection boxes are now — temporarily — gone!

**Comment by kdholland** [comment]
🙌 looks good! thank you!
