### ISSUE TITLE
The Protocol-relative URLs in CSS imports break in side-by-side viewer but not in main viewer

### ISSUE THREAD

**Issue by jacobbf** [superhi/editor-issues#14]
Using @import to bring in a font in CSS doesn't work in side by side view if it has a protocol relative url but it works fine in the main viewer. Having an https URL works on both (Google fonts gives you an https link now so at least it won't be an issue there). 

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/23109850/62156797-b375cd00-b2d9-11e9-87ad-084d73de2023.gif)

**Comment by kdholland** [comment]
thanks @jacobbf ! Could you please include the steps to reproduce this?

**Comment by artcommacode** [comment]
lol well I guess that makes sense, no way Google is sending us fonts over the `blob://` protocol. thanks for the catch @jacobbf!
