### ISSUE TITLE
Saving project versions not working in new editor

### ISSUE THREAD

**Issue by kdholland** [superhi/editor-issues#18]
**Describe the bug**
Saving project versions not working in new editor

**To Reproduce**
Steps to reproduce the behaviour:
1. Click into a project and go to Project Settings > Versions
2. Enter a title and save the project
3. Project reads as 'Saving...' but never completes

**Expected behaviour**
Project saves and is available to view + revert as in old editor.

**Screenshots**
![image](https://user-images.githubusercontent.com/31701255/62314512-35443280-b461-11e9-9806-75ff35708f04.png)

**Device (please complete the following information):**
 - OS:  macOS 10.14.5
 - Browser:  Google Chrome 76.0.3809.87 

**Additional context**
I'm not sure if this was intentional but I also noticed the Description box is gone in the new editor.

**Comment by artcommacode** [comment]
@kdholland there were various packages missing from upgrading ember and copying stuff over from the dotcom site. let me know if this works for you now!
