### ISSUE TITLE
Split Screen Preview [JS Script]

### ISSUE THREAD

**Issue by ackristen** [superhi/editor-issues#19]
**Describe the bug**
When previewing code in split screen mode, JS script is not fully loading (or showing up?)

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to split screen preview and click for images to appear.
2. Upon click you will see an outline of image that is supposed to appear on screen.

**Expected behaviour**
JS script in this instance involves clicking for images to appear.

**Screenshots**
New Editor Split Screen Preview:
<img width="1552" alt="Screen Shot 2019-08-06 at 4 30 42 PM" src="https://user-images.githubusercontent.com/37456705/62575298-73c65c80-b868-11e9-814a-c99cf334a6da.png">

Old Editor Preview:
<img width="1552" alt="Screen Shot 2019-08-06 at 4 30 51 PM" src="https://user-images.githubusercontent.com/37456705/62575325-817be200-b868-11e9-82e9-455e77d7ca92.png">

**Device (please complete the following information):**
 - OS: macOS 10.14.4
 - Browser: Google Chrome 
Version 76.0.3809.87 (Official Build) (64-bit)

**Comment by kdholland** [comment]
@artcommacode This is a new one - any thoughts on what's causing this?

Files here: http://robbie-alvarez-draft.superhi.com/_src

**Comment by artcommacode** [comment]
oh for the record i know _exactly_ what's happening here and it was a deliberate choice to leave it like this but i got to thinking about it last night and maybe there's a better way of handling issues like this? what this space!

**Comment by artcommacode** [comment]
okay @ackristen let me know if this fixes things up for you!
