### ISSUE TITLE
Blank, scrollable space at the bottom of code 

### ISSUE THREAD

**Issue by kdholland** [superhi/editor-issues#2]
**Describe the bug**
Lots of blank space at the end of code docs - they're not part of the code and it isn't possible to remove them.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a project in the new editor.
2. Scroll down to the bottom of any page, stylesheet, or script. 
4. See blank space, not possible to delete it. 

**Expected behaviour**
The page to end where the code ends, not being able to scroll up past end of code.

**Screenshots**
<img width="1289" alt="Screen Shot 2019-06-03 at 12 34 04 PM" src="https://user-images.githubusercontent.com/31701255/58799190-89b36900-85fc-11e9-8ee5-45b5552e866d.png">
<img width="1298" alt="Screen Shot 2019-06-03 at 12 34 53 PM" src="https://user-images.githubusercontent.com/31701255/58799192-89b36900-85fc-11e9-8f05-e2b462c9b8d9.png">

**Device (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser:Google Chrome Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by artcommacode** [comment]
@kdholland this is a feature not a bug!

this particular feature is known as "scroll past end" and it particularly useful when you want to look at some code in a file and don't want to be staring at the bottom of the screen while working on it. it's used in quite a few modern editors these days!

**Comment by kdholland** [comment]
@artcommacode ah - i had no idea! cool! :)
