### ISSUE TITLE
Preview Stuck

### ISSUE THREAD

**Issue by jacobbf** [superhi/editor-issues#20]
**Describe the bug**
The preview sticking bug is back! And it's backwards this time! Resize handle will skip around, jumping a good distance in front of the code. If you immediately drag it back it will shrink, but if you let go it will get stuck, covering the code. It's mysterious but sometimes I can get it unstuck by grabbing the handle and sometimes I can't. See screenshot.

**To Reproduce**
1. Open preview
2. Drag, let go
3. Repeat until stuck

**Expected behavior**
Preview does not jump, matches movement of the mouse and drags back when I grab it.

**Screenshots**
![preview jumping](https://user-images.githubusercontent.com/23109850/63717255-cb2b6d00-c815-11e9-9c2a-f08f0d2a1e60.gif)

**Device (please complete the following information):**
 - OS: macOS 10.14.6
 - Browser: Google Chrome 76.0.3809.100

**Additional context**
Reported by a student and reproduced.

**Comment by kdholland** [comment]
Assigning this to you @artcommacode , but keeping @jacobbf and myself assigned in case we are able to provide any more details on this bug! 

So far I haven't been able to reproduce it in the projects I've checked on, but will update if that changes.
