### ISSUE TITLE
The Protocol-relative URLs Issue (Returns)

### ISSUE THREAD

**Issue by jacobbf** [superhi/editor-issues#22]
**Describe the bug**
So I knew this seemed familiar. the protocol relative URL issue we were having with CSS imports working in the full preview but not working in the side-by-side is back, just a bit more of a problem this time. 

Protocol protocol agnostic URLs (like the one's Contentful returns for assets) won't load in the side by side preview. This is (in particular) an issue for anyone doing the Ajax and APIs course.

**To Reproduce**
Steps to reproduce the behaviour:
1. Load up an editor project.
2. Try to load any content (image, import etc.) with a protocol agnostic url. Here's one from the Uova project I was testing with `//images.ctfassets.net/vvetuscmvdoo/3tfHgVNT9gWP9qMKeqkW3O/ef66f951de599bf77c7075be114d94e6/image4.jpg`
3. See it not appear in the side-by-side
4. See it appear in full preview

**Expected behaviour**
URLs load in both the side-by-side and the full preview

**Screenshots**
![broken urls](https://user-images.githubusercontent.com/23109850/65547389-62541500-dee7-11e9-804c-d7b03425764d.gif)

**Device**
 - OS: macOS 10.14.6
 - Browser: Google Chrome Version 77.0.3865.90 (Official Build) (64-bit)

**Comment by artcommacode** [comment]
Hmm yeah we fixed this for HTML elements but not within JS files. I'll have a think!

**Comment by artcommacode** [comment]
@jacobbf do you have a link to your project? I've just realised that the live project URL is only an example and doesn't use Contentful

**Comment by artcommacode** [comment]
@jacobbf paging you again for a link where this happens!

**Comment by jacobbf** [comment]
Totally missed this (thanks for the reminder @ackristen)! [Here's](http://uova-43.superhi.com/) the link to my project. They show up fine on the site proper, just awol in the side-by-side

**Comment by artcommacode** [comment]
Hmm, unfortunately there's no way of fixing this, we'd need some method of rewriting URLs on-the-fly which we just don't have: we'd need a sandbox to run code the code in, inspect it, and then modify the original code, etc.

I'm surprised Contentful is insisting on using protocol-relative URLs — they're entirely unnecessary now that HTTPS is as fast as HTTP — I can see there were two issues to remove them but they were closed with due to lack of activity. Maybe I'll make a pull request?!

**Comment by artcommacode** [comment]
Added a note to the video where students set this section up — https://www.superhi.com/student/ajax-apis/uova/gxj7er5pxv — with a one-line fix for them.
