### ISSUE TITLE
Settings tab is blank on some projects

### ISSUE THREAD

**Issue by alexvissaridis** [superhi/editor-issues#27]
**Describe the bug**
On some projects, the settings tab on the editor generates a blank white page rather than any of the normal settings. This happens on [the project file](https://future-editor.superhi.com/projects/74069) for [my portfolio website](https://www.alexvissaridis.work/), for example, but not on my Superhi lesson sites. My portfolio website is much, much larger than any other project I own.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open the Editor
2. Click on a Project
3. Click on the Settings tab
4. White page appears

**Expected behaviour**
Settings page displays correctly and allows me to edit settings for the project.

**Screenshots**
<img width="1280" alt="Screenshot 2021-02-03 at 12 12 00" src="https://user-images.githubusercontent.com/11269445/106745870-9f6f0200-6619-11eb-9ebe-b7d63f3abc1a.png">

**Device (please complete the following information):**
 - OS: macOS 11.1
 - Browser: Google Chrome 88.0.4324.96

**Additional context**
Console error reads:
`Failed to load resource: the server responded with a status of 404 (Not Found)` on `_fonts.css:1`

**Comment by artcommacode** [comment]
thanks for the detailed issue @alexvissaridis!
