### ISSUE TITLE
Fonts smoothing needed on Firefox

### ISSUE THREAD

**Issue by indaviande** [superhi/editor-issues#3]
**Description**
On Firefox, fonts seems too bold. 
I think these lines are just missing :
  text-rendering: optimizeLegibility;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale; 

**Screenshots**
![Capture d’écran 2019-06-04 à 18 18 49](https://user-images.githubusercontent.com/33333630/58896022-7637f900-86f5-11e9-8b94-b8f03285f12c.png)

**Device:**
 - OS: macOS 10.14.5 (18F132)
 - Browser: Firefox Quantum 67.0 (64 Bits)

**Comment by kdholland** [comment]
Looks like a Firefox-specific issue :) thanks for reporting, @indaviande !

**Comment by artcommacode** [comment]
`-moz-osx-font-smoothing: grayscale;` was missing, yes. This is actually a carry-over from the current editor but I'm happy to fix it up for the beta!
