### ISSUE TITLE
when adding a font from google fonts into CSS it says CCS selector doesn't exist with unhappy face (tried it in the other editor and it worked fine there) 

### ISSUE THREAD

**Issue by aixalj** [superhi/editor-issues#30]
**Describe the bug**
when adding a font from google fonts into CSS it says CSS selector doesn't exist with an unhappy face, I tried it in the older editor version (to see if any of the code might have been wrong) and it worked fine there. (I have also added another google font underneath to see if that worked and it hasn't)

**To Reproduce**
Steps to reproduce the behaviour:

1. Start by getting a google font import code 
2. Add it to the top of CSS page
3. See the unhappy face and 'css selector doesn't exist' message 

**Expected behaviour**
that the google font piece of code would be recognised in the editor and that font could be applied in CSS 

**Screenshots**
<img width="1281" alt="Screenshot 2021-02-24 at 15 43 59" src="https://user-images.githubusercontent.com/64977600/109017073-1ea2a380-76b7-11eb-8d1f-61965747d04a.png">

**Device (please complete the following information):**

- OS: MacOS 11.2.1 
- Browser: Chrome
- Version: 88.0.4324.192

**Additional context**

**Comment by artcommacode** [comment]
Oh, I probably should've added this one myself! Yes thanks @aixalj this is an issue we're actively tracking internally, it turns out that the CSS parser we use doesn't like semi colons in `@import` urls, everything will still work correctly it's just that the editor tells you there's an error when there actually isn't

**Comment by aixalj** [comment]
oh ok thanks! will keep this in mind :)
