### ISSUE TITLE
Body selector text black in media query but styles are applying

### ISSUE THREAD

**Issue by hollylouisarose** [superhi/editor-issues#31]
**Describe the bug**
In media queries, the body selector text is showing as black not red like other selectors. Styles within selectors are applying fine. Other selector titles appear red as usual. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Write media query
2. Write style for body
4. Body selector text is black 

**Expected behaviour**
Body selector to be red like other css selectors

**Screenshots**

**Device (please complete the following information):**
 - OS: [e.g. macOS 10.15.6 ]
 - Browser: [e.g. Google Chrome 88.0.4324.192]

**Additional context**
Have tested in chrome icognito window and appears there also.
![bodycss](https://user-images.githubusercontent.com/72203800/109193605-76610d80-7790-11eb-899d-756a0f624099.png)

**Comment by artcommacode** [comment]
Ah, this is interesting! Unfortunately the issue here is in Microsoft's side of things and I don't have any control over how their parser works directly. I'll be sure to pass it on though 🙏
