### ISSUE TITLE
Problem with publishing new changes on the site

### ISSUE THREAD

**Issue by tangaroo** [superhi/editor-issues#33]
**Describe the bug**
Tried publishing some changes on the new editor but it was not showing up on the live site and had to revert to using the old editor and those changes were published.

**To Reproduce**
Steps to reproduce the behaviour:
1. Made code changes in sub editor.
2. Hit publish changes and checked on versions - new published site was saved as a new version.
3. Checked live site and published site from the version history by clicking on "view"
4. Changes were not published.

**Expected behaviour**
Expected the changes to be live right away, a new version of the recently published site was also added to the version but the new changes were not live.

**Device (please complete the following information):**
 - OS: Mac OS 11.1
 - Browser: Google Chrome Version 89.0.4389.90

**Comment by artcommacode** [comment]
Thanks for the bug report @tangaroo, this should now be fixed!
