### ISSUE TITLE
Publishes don't get updated

### ISSUE THREAD

**Issue by AdamHasma** [superhi/editor-issues#34]
**Describe the bug**
[My site](https://mnmal.superhi.com) doesn't get updated when I updated the code. On the editor preview however it gets updated. Used the new editor. Did this yesterday.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to one of your existing project and change something
2. Click on publish

**Expected behaviour**
Changes to be updated within seconds or minutes at least.

**Device (please complete the following information):**
 - OS: Windows
 - Browser: Google Chrome version 89.0.4389.114

**Comment by artcommacode** [comment]
Hi @AdamHasma this issue was fixed this morning, could you please make sure you're on the latest version of the Editor by doing a hard refresh — shift + command + R in Chrome on Mac — and trying again? Thank you!
