### ISSUE TITLE
Issues uploading index.html and style.css to new editor vs beta.superhi.com editor

### ISSUE THREAD

**Issue by pixelspencil** [superhi/editor-issues#36]
**Describe the bug**
I was using the new editor but had to switch back for some of the tutorials in the foundation course due to an issue with certain file uploads if they already exist in the editor, in this instance index.html and style.css

**To Reproduce**
Steps to reproduce the behaviour:
1. Upload assets in to the 'Drag and drop files or click to upload' box
2. When uploaded view both index.html and style.css and notice no change
3. Switch back to beta.superhi.com and view both index.html and style.css and notice code has changed

**Expected behaviour**
Expected to behave much like the editor at beta.superhi.com

**Device (please complete the following information):**
 - OS: macOS 11.2.3
 - Browser: Firefox Developer Edition 89.0b2 (64-bit)

**Comment by artcommacode** [comment]
@pixelspencil if you refresh the project after uploading the files to the beta Editor (https://subeditor.superhi.com, despite the URL for the other Editor it's actually the v1 Editor!) do you see the changes?

**Comment by pixelspencil** [comment]
@artcommacode It does indeed update but until I do that the little browse box also gets stuck - will this eventually work like it does in the editor I have been using?

<img width="302" alt="Screenshot 2021-04-21 at 11 48 15" src="https://user-images.githubusercontent.com/1231005/115542688-706f4080-a298-11eb-9b6b-96b3a9c8cf02.png">

Also noted that I will now use or try to remember to use editor.superhi.com 👍🏻

**Comment by artcommacode** [comment]
@pixelspencil this has all been fixed now. thanks for the bug report 👍

**Comment by pixelspencil** [comment]
Nice one - thank you @artcommacode
