### ISSUE TITLE
SSL certificate has expired

### ISSUE THREAD

**Issue by tangaroo** [superhi/editor-issues#37]
**Describe the bug**
I have noticed that my domain i.e: cassandratang.me is showing an error, screenshot attached. I contacted iwantmyname and they have informed me that the SSL certificate has expired. Another member has mentioned this issue, possibly only happening after she published with the new editor - which could be the same case here as well. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to 'cassandratang.me'
2. Error is shown.

**Expected behaviour**
The site should open normally without any errors. 

**Screenshots**
<img width="785" alt="Screenshot 2021-04-26 at 09 20 27" src="https://user-images.githubusercontent.com/75140334/116044004-ae8dab00-a670-11eb-9392-8807b3d0d523.png">

**Device (please complete the following information):**
 - OS: macOS 11.1
 - Browser: Google Chrome

**Comment by artcommacode** [comment]
Hi @tangaroo thanks for the issue, we're currently looking into it. Note that non-editor issues like this should be sent to hi@superhi.com and one of the staff there always will be able to help you out!
