### ISSUE TITLE
MP3 files are not playing on preview

### ISSUE THREAD

**Issue by indaviande** [superhi/editor-issues#4]
**Describe the bug**
On this project : [https://subeditor.superhi.com/projects/29327], when you click on plop.mp3, the small player appears but after click on Play, Play icon switch to Pause but the sound is never played.

**Screenshots**
![Capture d’écran 2019-06-04 à 18 24 12](https://user-images.githubusercontent.com/33333630/58896295-fcecd600-86f5-11e9-8a1a-8604b4f36926.png)

**Device:**
 - OS: macOS 10.14.5
 - Browser: Firefox Quantum 67.0

**Comment by kdholland** [comment]
thanks so much for reporting this @indaviande !

I'm able to get mp3 previews working in the new editor in Firefox - could you try this one again? If it's still not working, could you please send the file to me at kendall@superhi.com?

**Comment by indaviande** [comment]
My pleasure, Kendall.
Yes, mp3s playing is working now!
