### ISSUE TITLE
Editor crashing upon opening saved projects

### ISSUE THREAD

**Issue by Nick-Fiasco** [superhi/editor-issues#5]
**Describe the bug**
On opening up an already existing saved project in the new editor the page crashed and became unresponsive. Can't click on anything (even right click to look for any console logs/errors) Have to force page to stop and exit. White screen of doom..

**To Reproduce**
1. Go to https://subeditor.superhi.com/
2. Log in to account
3. Click on project (https://subeditor.superhi.com/projects/34730)

**Expected behaviour**
Opening the project, loading files into the left hand navigation and show the project preview in the right hand split window

**Device**
 - OS: macOS 10.14.5
 - Browser: Chrome Version 75.0.3770.90

The editor works great when adding a new project though!

**Comment by kdholland** [comment]
Thanks for reporting @Nick-Fiasco ! Does this happen for all of your projects or just this one?

**Comment by Nick-Fiasco** [comment]
Hey @kdholland No problem!

Trying it out on my other projects I found it crashed on two out of the four.

The two where it was loading ok I noticed that it did take a few seconds to load and I wasn't quite sure if it was still loading or not until the content popped in suddenly. (about 5-6 seconds load time from initial editor UI load until it was ready to use and showing up the files/preview)

**Comment by kdholland** [comment]
Thank you @Nick-Fiasco ! Looking into it now :)

**Comment by kdholland** [comment]
Indeed you were right @artcommacode ! Looks like the `a_tachyons.css` file is the one where the editor has an issue - when I reproduced this, that file wouldn't upload and crashed my browser.

**Comment by artcommacode** [comment]
Yep, so it turns out the Editor doesn't enjoy loading in and parsing over 2000 CSS selectors!

**Comment by artcommacode** [comment]
Thanks for catching that @Nick-Fiasco! I've just added in some basic large-file handling to the Editor that should fix this up for you. If you find that you're still having problems with the Editor then just re-open this issue 🙏
