### ISSUE TITLE
CSS not applied to side-by-side preview in Safari

### ISSUE THREAD

**Issue by nourmalaeb** [superhi/editor-issues#6]
I use Safari as my default browser and all my projects in the beta SuperHi editor are not getting any CSS or JS included. I logged on in Firefox and things seem to work as expected. 

**Screenshots**
<img width="1380" alt="Screen Shot 2019-06-18 at 16 35 09" src="https://user-images.githubusercontent.com/2767880/59717951-0b072000-91e7-11e9-83bc-2722400b4b0f.png">

**Device:**
 - OS: macOS 10.14.5
 - Browser: Safari 12.1.1

**Comment by elishacohen** [comment]
This is also happening to me in chrome:
<img width="1138" alt="Screen Shot 2019-06-19 at 10 49 17 AM" src="https://user-images.githubusercontent.com/51991222/59750877-cda2a100-927f-11e9-86f6-92c44f19685a.png">

**Comment by artcommacode** [comment]
Hi @elishacohen could you please open a separate issue with all of your details there, including a link to your live site? 

@nourmalaeb's issue is to do with Safari blocking Blob URLs with hashes in them — an undocumented "feature" that I just learnt about today! — but this isn't a problem with Chrome.

**Comment by elishacohen** [comment]
Sure, I can do that

**Comment by kdholland** [comment]
This one looks good to me! @nourmalaeb thanks for reporting this one 😄  Could you please confirm all looks good for you?

**Comment by nourmalaeb** [comment]
The good news is that the CSS is being applied now! The bad news is that my images aren't showing up... though they do on the live site https://nm-jenna-buchholz-photography.superhi.com

<img width="1638" alt="Screen Shot 2019-06-20 at 09 50 38" src="https://user-images.githubusercontent.com/2767880/59854407-de671b80-9340-11e9-885d-d4f6cb0e71dc.png">

Looks like there's still a "blob" in the image url? I don't know what blobs are.

**Comment by artcommacode** [comment]
Hi @nourmalaeb, thanks for checking again! Do these images in particular work in Firefox for you? 

I believe this may be a separate — browser independent — issue effecting `srcset`s where images have been prefetched in a worker.

**Comment by nourmalaeb** [comment]
You're right—they don't work on firefox either. I'll close this issue out then!

**Comment by artcommacode** [comment]
Great! I'll open a separate issue for the `srcset` problem then.
