### ISSUE TITLE
Full preview not updating

### ISSUE THREAD

**Issue by kdholland** [superhi/editor-issues#9]
Hey @artcommacode ! Have noticed this one a few times and finally getting around to reporting it - let me know if you've got any questions.

**Describe the bug**
The full preview isn't staying up to date with code changes.

**To Reproduce**
Steps to reproduce the behaviour:
1. Work on some code changes in the code/split screen view 
2. Click on Preview icon in the sidebar
3. Code changes aren't reflected in full preview
4. Click refresh icon at the bottom - code changes still don't show up

**Expected behaviour**
Full preview should be up to date, or update after clicking refresh icon.

**Screenshots**

*Code view with split screen preview - code is up to date:*
![image](https://user-images.githubusercontent.com/31701255/60619857-95cf4980-9da7-11e9-81dd-fb76e6795821.png)

*After clicking on Preview icon - code isn't updated:*
![image](https://user-images.githubusercontent.com/31701255/60619865-9f58b180-9da7-11e9-9482-450514863191.png)

**Device (please complete the following information):**
 - OS: macOS 10.14.5
 - Browser: Version 75.0.3770.100

**Comment by kdholland** [comment]
just a note that refreshing the *browser* seems to do the trick, but clicking the refresh icon in the bottom bar does not.

**Comment by artcommacode** [comment]
Ahh yes the full-page Preview hasn't been yet been touched in the new Editor so is currently relying on some old code that has since been trimmed!

**Comment by artcommacode** [comment]
Fixed in https://github.com/superhi/editor/commit/6ed1ad56c8cb4e6bfc28934b8d61942facd92af8, we now have manual reloading in the full-screen preview again.

**Comment by kdholland** [comment]
Yep, manual reloading looks good - thanks @artcommacode !
